# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ux6SF15wvSYA83sFIE16KJlKJ-RUnyUA
"""

n=int(input());
sum=0;
last=0;
while n>0:
  last=n%10;
  sum=sum+last;
  n=n//10;
print(sum)

a=int(input());
rev=0;
while a>0:
  rev=rev*10+(a%10);
  a=a//10;
print(rev);

a=int(input());
n=len(str(a));
t=a;
sum=0
last=0
while(a>0):
  last=a%10;
  sum=sum+last**n;
  a=a//10;
print(sum)
if(sum==t):
  print("Armstrong number")
else:
  print("Not a armstrong number")

n=int(input())
a,b=0,1
count=0
while count<n:
  print(a)
  a,b=b,a+b
  count+=1

def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True

n = int(input("Enter a number (N): "))
prime_count = 0
for number in range(1, n + 1):
    if is_prime(number):
        prime_count += 1

print(prime_count)

def check_even_odd(number):
    if number % 2 == 0:
        return "Even"
    else:
        return "Odd"
a=int(input())
print(a,"is",check_even_odd(a))

def factorial(n):
    if n < 0:
        return
    elif n == 0:
        return 1
    else:
        result = 1
        for i in range(1, n + 1):
            result *= i
        return result

# Example usage:
number = int(input())
print(factorial(number))

def lt(a,b,c):
  return max(a,b,c)
a=int(input())
b=int(input())
c=int(input())
print(max(a,b,c))

def count_vowels(input_string):
    vowels = "aeiouAEIOU"
    vowel_count = 0
    for char in input_string:
        if char in vowels:
            vowel_count += 1
    return vowel_count

# Example usage:
A =input()
print(count_vowels(A))

def add(num1, num2):
    return num1 + num2

def subtract(num1, num2):
    return num1 - num2

def multiply(num1, num2):
    return num1 * num2

def divide(num1, num2):
    if num2 == 0:
        return "Error: Cannot divide by zero"
    return num1 / num2

num1=int(input())
num2=int(input())

print("Choose operation:")
print("1. Add")
print("2. Subtract")
print("3. Multiply")
print("4. Divide")

choice = int(input("Enter choice (1/2/3/4): "))

# Perform operation
if choice == 1:
    print("Result:", add(num1, num2))
elif choice == 2:
    print("Result:", subtract(num1, num2))
elif choice == 3:
    print("Result:", multiply(num1, num2))
elif choice == 4:
    print("Result:", divide(num1, num2))
else:
    print("Invalid choice")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile operations.py
# def square(num):
#     return num * num
# 
# def cube(num):
#     return num * num * num

import operations as op

n = int(input("Enter a number: "))

print(square(n))
print(cube(n))

import random

# Generate random number between 1 and 100
secret_number = random.randint(1, 100)

print("Guess the number between 1 and 100!")

while True:
    guess = int(input("Enter your guess: "))

    if guess < secret_number:
        print("Too low! Try again.")
    elif guess > secret_number:
        print("Too high! Try again.")
    else:
        print("You guessed it right:")
        break

import math

# Square root
num = 16
print(math.sqrt(num))

# Power (x^y)
x = 2
y = 5
print(math.pow(x, y))

# Factorial
n = 5
print(math.factorial(n))

students = []

# Function to add student
def add_student(roll_no, name, marks):
    student = {"roll_no": roll_no, "name": name, "marks": marks}
    students.append(student)
    print("Student added successfully!")

# Function to view all students
def view_students():
    if not students:
        print("No students found.")
    else:
        print("\n--- Student List ---")
        for s in students:
            print("Roll No:", s["roll_no"], "| Name:", s["name"], "| Marks:", s["marks"])

# Function to search student by roll number
def search_student(roll_no):
    for s in students:
        if s["roll_no"] == roll_no:
            print("Student Found -> Roll No:", s["roll_no"], ", Name:", s["name"], ", Marks:", s["marks"])
            return
    print("Student not found.")

# Function to calculate average marks
def calculate_average():
    if not students:
        print("No students to calculate average.")
    else:
        total = sum(s["marks"] for s in students)
        avg = total / len(students)
        print("Average Marks of all students:", avg)

# Menu-driven program
while True:
    print("\n--- Student Management System ---")
    print("1. Add Student")
    print("2. View All Students")
    print("3. Search Student by Roll No")
    print("4. Calculate Average Marks")
    print("5. Exit")

    choice = int(input("Enter your choice (1-5): "))

    if choice == 1:
        roll_no = int(input("Enter Roll No: "))
        name = input("Enter Name: ")
        marks = int(input("Enter Marks: "))
        add_student(roll_no, name, marks)
    elif choice == 2:
        view_students()
    elif choice == 3:
        roll_no = int(input("Enter Roll No to search: "))
        search_student(roll_no)
    elif choice == 4:
        calculate_average()
    elif choice == 5:
        print("Exiting... Goodbye!")
        break
    else:
        print("Invalid choice. Please try again.")